"""change telegram_id to bigint

Revision ID: 2a6c7f23cd10
Revises: 4996c8ab341e
Create Date: 2025-04-28 10:26:22.382610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6c7f23cd10'
down_revision: Union[str, None] = '4996c8ab341e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_reports_recipient_id_users', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['recipient_id'], ['id'])
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('fk_reports_recipient_id_users', 'reports', 'users', ['recipient_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
